name: Exporting of DB
 
on: workflow_dispatch
 
jobs:
 
    deploy:
 
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        steps:
 
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
            service_account_email: ${{ secrets.EMAIL }}
            service_account_key: ${{ secrets.CREDENTIALS }}
            export_default_credentials: true
 
        - name: Exporting DB
          uses: gcloud sql export sql test-db gs://jatin-test
