name: Exporting of DB

on: push

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
            service_account_email: ${{ secrets.EMAIL }}
            service_account_key: ${{ secrets.CREDENTIALS }}

        - name: Project Config
          run: gcloud config set project cs-tmpl-test

        - name: Exporting DB
          run: gcloud sql export sql test-db gs://jatin-test
