name: DB Export/import

on: workflow_dispatch

env:
     OPERATION: gcloud sql import sql db-test1 gs://jatin-test/hello.sql.gz

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
            service_account_email: ${{ secrets.EMAIL }}
            service_account_key: ${{ secrets.CREDENTIALS }}

        - name: Project Config
          run: gcloud config set project cs-tmpl-test

        - name: Exporting DB
          run: gcloud sql export sql test-db gs://jatin-test/hello.sql.gz
          
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            GCP_PROJECT_ID: ${{ secrets.TARGET_PROJECT_ID }}
            service_account_email: ${{ secrets.TARGET_EMAIL }}
            service_account_key: ${{ secrets.TARGET_CREDENTIALS }}
            
        - name: Project Config
          run: gcloud config set project cs-tmpl-dev
            
        - name: Importing DB
          run:  gcloud sql operations wait OPERATION ${OPERATION} --timeout=unlimited
          
            
    
