name: Importing of DB

on: push

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            GCP_PROJECT_ID: ${{ secrets.TARGET_PROJECT_ID }}
            service_account_email: ${{ secrets.TARGET_EMAIL }}
            service_account_key: ${{ secrets.TARGET_CREDENTIALS }}

        - name: Project Config
          run: gcloud config set project cs-tmpl-dev

        - name: Exporting DB
          run: gcloud sql import sql test-db gs://jatin-test/hello.sql
